#!/bin/bash
reps=(
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	' '
	'\x20'
	'\x21'
	'\x22'
	'\x23'
	'\x24'
	'\x25'
	'\x26'
	'\x27'
	'\x28'
	'\x29'
	'\x2a'
	'\x2b'
	'\x2c'
	'\x2d'
	'\x2e'
	'\x2f'
	'\x30'
	'\x31'
	'\x32'
	'\x33'
	'\x34'
	'\x35'
	'\x36'
	'\x37'
	'\x38'
	'\x39'
	'\x3a'
	'\x3b'
	'\x3c'
	'\x3d'
	'\x3e'
	'\x3f'
	'\x40'
	'\x41'
	'\x42'
	'\x43'
	'\x44'
	'\x45'
	'\x46'
	'\x47'
	'\x48'
	'\x49'
	'\x4a'
	'\x4b'
	'\x4c'
	'\x4d'
	'\x4e'
	'\x4f'
	'\x50'
	'\x51'
	'\x52'
	'\x53'
	'\x54'
	'\x55'
	'\x56'
	'\x57'
	'\x58'
	'\x59'
	'\x5a'
	'\x5b'
	'\x5c'
	'\x5d'
	'\x5e'
	'\x5f'
	'\x60'
	'\x61'
	'\x62'
	'\x63'
	'\x64'
	'\x65'
	'\x66'
	'\x67'
	'\x68'
	'\x69'
	'\x6a'
	'\x6b'
	'\x6c'
	'\x6d'
	'\x6e'
	'\x6f'
	'\x70'
	'\x71'
	'\x72'
	'\x73'
	'\x74'
	'\x75'
	'\x76'
	'\x77'
	'\x78'
	'\x79'
	'\x7a'
	'\x7b'
	'\x7c'
	'\x7d'
	'\x7e'
	' '
	'\xe2\x82\xac'
	' '
	'\xe2\x80\x9a'
	'\xc6\x92'
	'\xe2\x80\x9e'
	'\xe2\x80\xa6'
	'\xe2\x80\xa0'
	'\xe2\x80\xa1'
	'\xcb\x86'
	'\xe2\x80\xb0'
	'\xc5\xa0'
	'\xe2\x80\xb9'
	'\xc5\x92'
	' '
	'\xc5\xbd'
	' '
	' '
	'\xe2\x80\x98'
	'\xe2\x80\x99'
	'\xe2\x80\x9c'
	'\xe2\x80\x9d'
	'\xe2\x80\xa2'
	'\xe2\x80\x93'
	'\xe2\x80\x94'
	'\xcb\x9c'
	'\xe2\x84\xa2'
	'\xc5\xa1'
	'\xe2\x80\xba'
	'\xc5\x93'
	' '
	'\xc5\xbe'
	'\xc5\xb8'
	'\xc2\xa0'
	'\xc2\xa1'
	'\xc2\xa2'
	'\xc2\xa3'
	'\xc2\xa4'
	'\xc2\xa5'
	'\xc2\xa6'
	'\xc2\xa7'
	'\xc2\xa8'
	'\xc2\xa9'
	'\xc2\xaa'
	'\xc2\xab'
	'\xc2\xac'
	' '
	'\xc2\xae'
	'\xc2\xaf'
	'\xc2\xb0'
	'\xc2\xb1'
	'\xc2\xb2'
	'\xc2\xb3'
	'\xc2\xb4'
	'\xc2\xb5'
	'\xc2\xb6'
	'\xc2\xb7'
	'\xc2\xb8'
	'\xc2\xb9'
	'\xc2\xba'
	'\xc2\xbb'
	'\xc2\xbc'
	'\xc2\xbd'
	'\xc2\xbe'
	'\xc2\xbf'
	'\xc3\x80'
	'\xc3\x81'
	'\xc3\x82'
	'\xc3\x83'
	'\xc3\x84'
	'\xc3\x85'
	'\xc3\x86'
	'\xc3\x87'
	'\xc3\x88'
	'\xc3\x89'
	'\xc3\x8a'
	'\xc3\x8b'
	'\xc3\x8c'
	'\xc3\x8d'
	'\xc3\x8e'
	'\xc3\x8f'
	'\xc3\x90'
	'\xc3\x91'
	'\xc3\x92'
	'\xc3\x93'
	'\xc3\x94'
	'\xc3\x95'
	'\xc3\x96'
	'\xc3\x97'
	'\xc3\x98'
	'\xc3\x99'
	'\xc3\x9a'
	'\xc3\x9b'
	'\xc3\x9c'
	'\xc3\x9d'
	'\xc3\x9e'
	'\xc3\x9f'
	'\xc3\xa0'
	'\xc3\xa1'
	'\xc3\xa2'
	'\xc3\xa3'
	'\xc3\xa4'
	'\xc3\xa5'
	'\xc3\xa6'
	'\xc3\xa7'
	'\xc3\xa8'
	'\xc3\xa9'
	'\xc3\xaa'
	'\xc3\xab'
	'\xc3\xac'
	'\xc3\xad'
	'\xc3\xae'
	'\xc3\xaf'
	'\xc3\xb0'
	'\xc3\xb1'
	'\xc3\xb2'
	'\xc3\xb3'
	'\xc3\xb4'
	'\xc3\xb5'
	'\xc3\xb6'
	'\xc3\xb7'
	'\xc3\xb8'
	'\xc3\xb9'
	'\xc3\xba'
	'\xc3\xbb'
	'\xc3\xbc'
	'\xc3\xbd'
	'\xc3\xbe'
	'\xc3\xbf'

	'\xd7\xaf' # HEBREW YOD TRIANGLE
	'\xe2\x83\xa4' # COMBINING ENCLOSING UPWARD POINTING TRIANGLE
	'\xe2\x8a\xbf' # RIGHT TRIANGLE
	'\xe2\x8e\x8a' # CIRCLED TRIANGLE DOWN
	'\xe2\x8f\x83' # DENTISTRY SYMBOL LIGHT VERTICAL WITH TRIANGLE
	'\xe2\x8f\x84' # DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH TRIANGLE
	'\xe2\x8f\x85' # DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH TRIANGLE
	'\xe2\x8f\xa9' # BLACK RIGHT-POINTING DOUBLE TRIANGLE
	'\xe2\x8f\xaa' # BLACK LEFT-POINTING DOUBLE TRIANGLE
	'\xe2\x8f\xab' # BLACK UP-POINTING DOUBLE TRIANGLE
	'\xe2\x8f\xac' # BLACK DOWN-POINTING DOUBLE TRIANGLE
	'\xe2\x8f\xad' # BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR
	'\xe2\x8f\xae' # BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR
	'\xe2\x8f\xaf' # BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR
	'\xe2\x8f\xb4' # BLACK MEDIUM LEFT-POINTING TRIANGLE
	'\xe2\x8f\xb5' # BLACK MEDIUM RIGHT-POINTING TRIANGLE
	'\xe2\x8f\xb6' # BLACK MEDIUM UP-POINTING TRIANGLE
	'\xe2\x8f\xb7' # BLACK MEDIUM DOWN-POINTING TRIANGLE
	'\xe2\x96\xb2' # BLACK UP-POINTING TRIANGLE
	'\xe2\x96\xb3' # WHITE UP-POINTING TRIANGLE
	'\xe2\x96\xb4' # BLACK UP-POINTING SMALL TRIANGLE
	'\xe2\x96\xb5' # WHITE UP-POINTING SMALL TRIANGLE
	'\xe2\x96\xb6' # BLACK RIGHT-POINTING TRIANGLE
	'\xe2\x96\xb7' # WHITE RIGHT-POINTING TRIANGLE
	'\xe2\x96\xb8' # BLACK RIGHT-POINTING SMALL TRIANGLE
	'\xe2\x96\xb9' # WHITE RIGHT-POINTING SMALL TRIANGLE
	'\xe2\x96\xbc' # BLACK DOWN-POINTING TRIANGLE
	'\xe2\x96\xbd' # WHITE DOWN-POINTING TRIANGLE
	'\xe2\x96\xbe' # BLACK DOWN-POINTING SMALL TRIANGLE
	'\xe2\x96\xbf' # WHITE DOWN-POINTING SMALL TRIANGLE
	'\xe2\x97\x80' # BLACK LEFT-POINTING TRIANGLE
	'\xe2\x97\x81' # WHITE LEFT-POINTING TRIANGLE
	'\xe2\x97\x82' # BLACK LEFT-POINTING SMALL TRIANGLE
	'\xe2\x97\x83' # WHITE LEFT-POINTING SMALL TRIANGLE
	'\xe2\x97\xa2' # BLACK LOWER RIGHT TRIANGLE
	'\xe2\x97\xa3' # BLACK LOWER LEFT TRIANGLE
	'\xe2\x97\xa4' # BLACK UPPER LEFT TRIANGLE
	'\xe2\x97\xa5' # BLACK UPPER RIGHT TRIANGLE
	'\xe2\x97\xac' # WHITE UP-POINTING TRIANGLE WITH DOT
	'\xe2\x97\xad' # UP-POINTING TRIANGLE WITH LEFT HALF BLACK
	'\xe2\x97\xae' # UP-POINTING TRIANGLE WITH RIGHT HALF BLACK
	'\xe2\x97\xb8' # UPPER LEFT TRIANGLE
	'\xe2\x97\xb9' # UPPER RIGHT TRIANGLE
	'\xe2\x97\xba' # LOWER LEFT TRIANGLE
	'\xe2\x97\xbf' # LOWER RIGHT TRIANGLE
	'\xe2\x9b\x9b' # HEAVY WHITE DOWN-POINTING TRIANGLE
	'\xe2\x9e\x9d' # TRIANGLE-HEADED RIGHTWARDS ARROW
	'\xe2\x9e\x9e' # HEAVY TRIANGLE-HEADED RIGHTWARDS ARROW
	'\xe2\x9e\x9f' # DASHED TRIANGLE-HEADED RIGHTWARDS ARROW
	'\xe2\x9e\xa0' # HEAVY DASHED TRIANGLE-HEADED RIGHTWARDS ARROW
	'\xe2\x9f\x81' # WHITE TRIANGLE CONTAINING SMALL WHITE TRIANGLE
	'\xe2\xa7\x8a' # TRIANGLE WITH DOT ABOVE
	'\xe2\xa7\x8b' # TRIANGLE WITH UNDERBAR
	'\xe2\xa7\x8c' # S IN TRIANGLE
	'\xe2\xa7\x8d' # TRIANGLE WITH SERIFS AT BOTTOM
	'\xe2\xa7\x8e' # RIGHT TRIANGLE ABOVE LEFT TRIANGLE
	'\xe2\xa7\x8f' # LEFT TRIANGLE BESIDE VERTICAL BAR
	'\xe2\xa7\x90' # VERTICAL BAR BESIDE RIGHT TRIANGLE
	'\xe2\xa7\xa8' # DOWN-POINTING TRIANGLE WITH LEFT HALF BLACK
	'\xe2\xa7\xa9' # DOWN-POINTING TRIANGLE WITH RIGHT HALF BLACK
	'\xe2\xa8\x9e' # LARGE LEFT TRIANGLE OPERATOR
	'\xe2\xa8\xa8' # PLUS SIGN WITH BLACK TRIANGLE
	'\xe2\xa8\xb9' # PLUS SIGN IN TRIANGLE
	'\xe2\xa8\xba' # MINUS SIGN IN TRIANGLE
	'\xe2\xa8\xbb' # MULTIPLICATION SIGN IN TRIANGLE
	'\xe2\xad\x8d' # DOWNWARDS TRIANGLE-HEADED ZIGZAG ARROW
	'\xe2\xad\xa0' # LEFTWARDS TRIANGLE-HEADED ARROW
	'\xe2\xad\xa1' # UPWARDS TRIANGLE-HEADED ARROW
	'\xe2\xad\xa2' # RIGHTWARDS TRIANGLE-HEADED ARROW
	'\xe2\xad\xa3' # DOWNWARDS TRIANGLE-HEADED ARROW
	'\xe2\xad\xa4' # LEFT RIGHT TRIANGLE-HEADED ARROW
	'\xe2\xad\xa5' # UP DOWN TRIANGLE-HEADED ARROW
	'\xe2\xad\xa6' # NORTH WEST TRIANGLE-HEADED ARROW
	'\xe2\xad\xa7' # NORTH EAST TRIANGLE-HEADED ARROW
	'\xe2\xad\xa8' # SOUTH EAST TRIANGLE-HEADED ARROW
	'\xe2\xad\xa9' # SOUTH WEST TRIANGLE-HEADED ARROW
	'\xe2\xad\xaa' # LEFTWARDS TRIANGLE-HEADED DASHED ARROW
	'\xe2\xad\xab' # UPWARDS TRIANGLE-HEADED DASHED ARROW
	'\xe2\xad\xac' # RIGHTWARDS TRIANGLE-HEADED DASHED ARROW
	'\xe2\xad\xad' # DOWNWARDS TRIANGLE-HEADED DASHED ARROW
	'\xe2\xad\xae' # CLOCKWISE TRIANGLE-HEADED OPEN CIRCLE ARROW
	'\xe2\xad\xaf' # ANTICLOCKWISE TRIANGLE-HEADED OPEN CIRCLE ARROW
	'\xe2\xad\xb0' # LEFTWARDS TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb1' # UPWARDS TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb2' # RIGHTWARDS TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb3' # DOWNWARDS TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb6' # NORTH WEST TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb7' # NORTH EAST TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb8' # SOUTH EAST TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xb9' # SOUTH WEST TRIANGLE-HEADED ARROW TO BAR
	'\xe2\xad\xba' # LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
	'\xe2\xad\xbb' # UPWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
	'\xe2\xad\xbc' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
	'\xe2\xad\xbd' # DOWNWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
	'\xe2\xae\x80' # LEFTWARDS TRIANGLE-HEADED ARROW OVER RIGHTWARDS TRIANGLE-HEADED ARROW
	'\xe2\xae\x81' # UPWARDS TRIANGLE-HEADED ARROW LEFTWARDS OF DOWNWARDS TRIANGLE-HEADED ARROW
	'\xe2\xae\x82' # RIGHTWARDS TRIANGLE-HEADED ARROW OVER LEFTWARDS TRIANGLE-HEADED ARROW
	'\xe2\xae\x83' # DOWNWARDS TRIANGLE-HEADED ARROW LEFTWARDS OF UPWARDS TRIANGLE-HEADED ARROW
	'\xe2\xae\x84' # LEFTWARDS TRIANGLE-HEADED PAIRED ARROWS
	'\xe2\xae\x85' # UPWARDS TRIANGLE-HEADED PAIRED ARROWS
	'\xe2\xae\x86' # RIGHTWARDS TRIANGLE-HEADED PAIRED ARROWS
	'\xe2\xae\x87' # DOWNWARDS TRIANGLE-HEADED PAIRED ARROWS
	'\xe2\xae\x8c' # ANTICLOCKWISE TRIANGLE-HEADED RIGHT U-SHAPED ARROW
	'\xe2\xae\x8d' # ANTICLOCKWISE TRIANGLE-HEADED BOTTOM U-SHAPED ARROW
	'\xe2\xae\x8e' # ANTICLOCKWISE TRIANGLE-HEADED LEFT U-SHAPED ARROW
	'\xe2\xae\x8f' # ANTICLOCKWISE TRIANGLE-HEADED TOP U-SHAPED ARROW
	'\xe2\xae\xa0' # DOWNWARDS TRIANGLE-HEADED ARROW WITH LONG TIP LEFTWARDS
	'\xe2\xae\xa1' # DOWNWARDS TRIANGLE-HEADED ARROW WITH LONG TIP RIGHTWARDS
	'\xe2\xae\xa2' # UPWARDS TRIANGLE-HEADED ARROW WITH LONG TIP LEFTWARDS
	'\xe2\xae\xa3' # UPWARDS TRIANGLE-HEADED ARROW WITH LONG TIP RIGHTWARDS
	'\xe2\xae\xa4' # LEFTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP UPWARDS
	'\xe2\xae\xa5' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP UPWARDS
	'\xe2\xae\xa6' # LEFTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP DOWNWARDS
	'\xe2\xae\xa7' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP DOWNWARDS
	'\xe2\xaf\x85' # BLACK MEDIUM UP-POINTING TRIANGLE CENTRED
	'\xe2\xaf\x86' # BLACK MEDIUM DOWN-POINTING TRIANGLE CENTRED
	'\xe2\xaf\x87' # BLACK MEDIUM LEFT-POINTING TRIANGLE CENTRED
	'\xe2\xaf\x88' # BLACK MEDIUM RIGHT-POINTING TRIANGLE CENTRED
	'\xe2\xaf\xac' # LEFTWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
	'\xe2\xaf\xad' # UPWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
	'\xe2\xaf\xae' # RIGHTWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
	'\xe2\xaf\xaf' # DOWNWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
	'\xf0\x9d\x85\x88' # MUSICAL SYMBOL TRIANGLE NOTEHEAD UP WHITE
	'\xf0\x9d\x85\x89' # MUSICAL SYMBOL TRIANGLE NOTEHEAD UP BLACK
	'\xf0\x9d\x85\x8a' # MUSICAL SYMBOL TRIANGLE NOTEHEAD LEFT WHITE
	'\xf0\x9d\x85\x8b' # MUSICAL SYMBOL TRIANGLE NOTEHEAD LEFT BLACK
	'\xf0\x9d\x85\x8c' # MUSICAL SYMBOL TRIANGLE NOTEHEAD RIGHT WHITE
	'\xf0\x9d\x85\x8d' # MUSICAL SYMBOL TRIANGLE NOTEHEAD RIGHT BLACK
	'\xf0\x9d\x85\x8e' # MUSICAL SYMBOL TRIANGLE NOTEHEAD DOWN WHITE
	'\xf0\x9d\x85\x8f' # MUSICAL SYMBOL TRIANGLE NOTEHEAD DOWN BLACK
	'\xf0\x9d\x85\x90' # MUSICAL SYMBOL TRIANGLE NOTEHEAD UP RIGHT WHITE
	'\xf0\x9d\x85\x91' # MUSICAL SYMBOL TRIANGLE NOTEHEAD UP RIGHT BLACK
	'\xf0\x9d\x85\x94' # MUSICAL SYMBOL TRIANGLE-ROUND NOTEHEAD DOWN WHITE
	'\xf0\x9d\x85\x95' # MUSICAL SYMBOL TRIANGLE-ROUND NOTEHEAD DOWN BLACK
	'\xf0\x9f\x94\xba' # UP-POINTING RED TRIANGLE
	'\xf0\x9f\x94\xbb' # DOWN-POINTING RED TRIANGLE
	'\xf0\x9f\x94\xbc' # UP-POINTING SMALL RED TRIANGLE
	'\xf0\x9f\x94\xbd' # DOWN-POINTING SMALL RED TRIANGLE
	'\xf0\x9f\x9b\x86' # TRIANGLE WITH ROUNDED CORNERS
	'\xf0\x9f\x9e\x80' # BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE
	'\xf0\x9f\x9e\x81' # BLACK UP-POINTING ISOSCELES RIGHT TRIANGLE
	'\xf0\x9f\x9e\x82' # BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE
	'\xf0\x9f\x9e\x83' # BLACK DOWN-POINTING ISOSCELES RIGHT TRIANGLE
	'\xf0\x9f\x9f\x95' # CIRCLED TRIANGLE
	'\xf0\x9f\x9f\x96' # NEGATIVE CIRCLED TRIANGLE
	'\xf0\x9f\xa0\x80' # LEFTWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x81' # UPWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x82' # RIGHTWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x83' # DOWNWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x84' # LEFTWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x05' # UPWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x06' # RIGHTWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x07' # DOWNWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x08' # LEFTWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x09' # UPWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x0a' # RIGHTWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\x0b' # DOWNWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
	'\xf0\x9f\xa0\xa0' # LEFTWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
	'\xf0\x9f\xa0\xa1' # UPWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
	'\xf0\x9f\xa0\xa2' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
	'\xf0\x9f\xa0\xa3' # DOWNWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
	'\xf0\x9f\xa0\xa4' # LEFTWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
	'\xf0\x9f\xa0\xa5' # UPWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
	'\xf0\x9f\xa0\xa6' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
	'\xf0\x9f\xa0\xa7' # DOWNWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
	'\xf0\x9f\xa0\xa8' # LEFTWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
	'\xf0\x9f\xa0\xa9' # UPWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
	'\xf0\x9f\xa0\xaa' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
	'\xf0\x9f\xa0\xab' # DOWNWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
	'\xf0\x9f\xa0\xac' # LEFTWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
	'\xf0\x9f\xa0\xad' # UPWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
	'\xf0\x9f\xa0\xae' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
	'\xf0\x9f\xa0\xaf' # DOWNWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
	'\xf0\x9f\xa0\xb0' # LEFTWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
	'\xf0\x9f\xa0\xb1' # UPWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
	'\xf0\x9f\xa0\xb2' # RIGHTWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
	'\xf0\x9f\xa0\xb3' # DOWNWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
	'\xf0\x9f\xa2\x90' # LEFTWARDS TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x91' # UPWARDS TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x92' # RIGHTWARDS TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x93' # DOWNWARDS TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x94' # LEFTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x95' # UPWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x96' # RIGHTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
	'\xf0\x9f\xa2\x97' # DOWNWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD

	'\xe2\x96\x80'
	'\xe2\x96\x84'

	# TODO: investigate unicode "Geometric Shapes"


)

#for i in {0..255}
#do
#  printf '%b' "${reps[$i]}"
#done
#printf '\n'
#printf '\n'

#for i in {0..255}
#for i in {0..257}
#for i in {0..440}
for i in {0..442}
do
  printf '%b' "${reps[$i]}"
  if (( (i + 1) % 16 == 0 )); then
    printf '\n'
  fi
done

printf '\n'


